name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        build_type:
          - Debug

        config:
          - qt_version: "5.15"
            macos_architectures: "x86_64"
          - qt_version: "6.6.0"
            macos_architectures: "x86_64;arm64"

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.config.qt_version }}
          cache: true

      - name: Install ninja-build tool (must be after Qt due PATH changes)
        uses: turtlesec-no/get-ninja@main

      - name: Make sure MSVC is found when Ninja generator is in use
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure project
        run: >
          cmake -S . -B ./build -G Ninja
          --warn-uninitialized
          -Werror=dev
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DENABLE_MAINTAINER_CFLAGS=${{ matrix.build_type == 'Debug' }}
          -DCMAKE_OSX_ARCHITECTURES="${{ matrix.config.macos_architectures }}"

      - name: Build project
        run: cmake --build ./build
